server:
  port: 8085

spring:
  application:
    name: pfp-pass
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.136.41.61:3306/pfp_app?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: TongMiao789654123
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 100
      # 链接超时时间，默认 30000(30 秒)
      connection-timeout: 60000
      # 空闲连接存活最大时间，默认 600000(10 分钟)
      idle-timeout: 60000
      # 连接将被测试活动的最大时间量
      validation-timeout: 3000
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000(30 分钟)
      max-lifetime: 180000
      # 连接到数据库时等待的最长时间(秒)
      login-timeout: 5
      # 池中维护的最小空闲连接数
      minimum-idle: 10
    tomcat:
      max-active: 200
      max-wait: 60000
      initial-size: 10
  # 文件上传配置  
  servlet:
    multipart:
      # 单个文件大小限制
      max-file-size: 10MB
      # 总上传数据大小限制
      max-request-size: 20MB
      # 是否启用分段上传
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO # "智能"模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      #      id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
      #      id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      #      id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false # 关闭控制台的 Banner 打印

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # 是否从请求 header 里读取 Token，必须为 true
  is-read-header: true
  # token 有效期，单位s 默认30天, -1代表永不过期 这里设置一天
  timeout: 86400
  # token 临时有效期 (指定时间内无操作就视为 token 过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为 true 时允许一起登录, 为 false 时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token (为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token)
  is-share: true
  # token 风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# SpringDoc 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: false

oss:
  qiniu:
    accessKey: 1An4FtjWnwe1DTgVdw8q7ioV_Sv8ywBPUDFolOt1
    secretKey: RDKriCRjU0cG8XGJ4SCWw5-e-zO2JblN9Pz6uXhg
    bucket: khy
    #// localFilePath: /path/to/local/file 文件下载到本地磁盘位置，可不配置（本文没有配置）
    #// domainOfBucket 中的域名为用户 bucket 绑定的域名 测试域名，只有30天有效期
    domainOfBucket: khy.hhhwww.top